export const PRICE_CHANGE_WEIGHT = [
  0.03, // PRICE_CHANGE_HOUR_WEIGHT
  0.07, // PRICE_CHANGE_DAY_WEIGHT
  0.1, // PRICE_CHANGE_7_DAY_WEIGHT
  0.15, // PRICE_CHANGE_30_DAY_WEIGHT
  0.25, // PRICE_CHANGE_60_DAY_WEIGHT
  0.4, // PRICE_CHANGE_90_DAY_WEIGHT
];

export const PRICE_THREAD: number = 5;
